version: "3.9"

services:
  moodsense:
    build: .
    container_name: moodsense-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      SQLITE_PATH: data/moodsense.db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
